-- Oracle Database Schema Inspector SQL Script
-- PRODUCTION_RESULTテーブルの構造とマイグレーション結果を確認

SET PAGESIZE 100;
SET LINESIZE 120;

PROMPT ================================================================================
PROMPT    ORACLE DATABASE SCHEMA INSPECTOR
PROMPT ================================================================================

PROMPT
PROMPT === 1. テーブル存在確認 ===
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN '✓ PRODUCTION_RESULT テーブルが存在します'
        ELSE '✗ PRODUCTION_RESULT テーブルが見つかりません'
    END AS TABLE_STATUS
FROM USER_TABLES 
WHERE TABLE_NAME = 'PRODUCTION_RESULT';

PROMPT
PROMPT === 2. カラム構造詳細 ===
COLUMN COLUMN_NAME FORMAT A20
COLUMN DATA_TYPE FORMAT A15
COLUMN DATA_LENGTH FORMAT 9999
COLUMN NULLABLE FORMAT A8
COLUMN DATA_DEFAULT FORMAT A15

SELECT 
    COLUMN_NAME,
    CASE 
        WHEN DATA_TYPE = 'NUMBER' AND DATA_PRECISION IS NOT NULL THEN 
            DATA_TYPE || '(' || DATA_PRECISION || ',' || NVL(DATA_SCALE, 0) || ')'
        WHEN DATA_TYPE IN ('VARCHAR2', 'CHAR') THEN 
            DATA_TYPE || '(' || DATA_LENGTH || ')'
        ELSE DATA_TYPE
    END AS DATA_TYPE,
    DATA_LENGTH,
    NULLABLE,
    SUBSTR(DATA_DEFAULT, 1, 15) AS DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
ORDER BY COLUMN_ID;

PROMPT
PROMPT === 3. 重要カラムのNULL制約状況 ===
SELECT 
    COLUMN_NAME,
    CASE 
        WHEN NULLABLE = 'Y' THEN '✓ NULL可 (制約削除済み)'
        ELSE '✗ NOT NULL (制約残存)'
    END AS CONSTRAINT_STATUS
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
AND COLUMN_NAME IN ('LINE_ID', 'MACHINE_ID', 'PART_ID', 'LINE', 'MACHINE', 'PART')
ORDER BY COLUMN_NAME;

PROMPT
PROMPT === 4. CHECK制約の確認 ===
SELECT 
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    SUBSTR(SEARCH_CONDITION, 1, 50) AS SEARCH_CONDITION
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
AND CONSTRAINT_TYPE = 'C'
AND SEARCH_CONDITION IS NOT NULL;

PROMPT
PROMPT === 5. インデックス情報 ===
SELECT 
    INDEX_NAME,
    UNIQUENESS,
    STATUS
FROM USER_INDEXES 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
ORDER BY INDEX_NAME;

PROMPT
PROMPT === 6. テーブル統計情報 ===
SELECT 
    NUM_ROWS,
    BLOCKS,
    AVG_ROW_LEN,
    LAST_ANALYZED
FROM USER_TABLES 
WHERE TABLE_NAME = 'PRODUCTION_RESULT';

PROMPT
PROMPT === 7. サンプルデータ (最大3件) ===
SELECT * FROM (
    SELECT 
        ID,
        QUANTITY,
        SUBSTR(LINE, 1, 10) AS LINE_SHORT,
        SUBSTR(MACHINE, 1, 10) AS MACHINE_SHORT,
        SUBSTR(PART, 1, 10) AS PART_SHORT,
        LINE_ID,
        MACHINE_ID,
        PART_ID,
        TO_CHAR(TIMESTAMP, 'YYYY-MM-DD HH24:MI') AS TIMESTAMP_STR
    FROM PRODUCTION_RESULT 
    ORDER BY ID
) WHERE ROWNUM <= 3;

PROMPT
PROMPT === マイグレーション検証結果 ===
PROMPT 以下のカラムがすべて NULL可 になっていればマイグレーション成功:
PROMPT - LINE, MACHINE, PART (文字列カラム)
PROMPT - LINE_ID, MACHINE_ID, PART_ID (外部キーカラム)
PROMPT
PROMPT ================================================================================

EXIT;