-- Oracle Database Schema Inspector SQL Script (Fixed Version)
-- PRODUCTION_RESULTテーブルの構造とマイグレーション結果を確認

SET PAGESIZE 100;
SET LINESIZE 120;

PROMPT ================================================================================
PROMPT    ORACLE DATABASE SCHEMA INSPECTOR - DETAILED ANALYSIS
PROMPT ================================================================================

PROMPT
PROMPT === 1. テーブル存在確認 ===
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN '✓ PRODUCTION_RESULT テーブルが存在します'
        ELSE '✗ PRODUCTION_RESULT テーブルが見つかりません'
    END AS TABLE_STATUS
FROM USER_TABLES 
WHERE TABLE_NAME = 'PRODUCTION_RESULT';

PROMPT
PROMPT === 2. 全カラム構造詳細 ===
COLUMN COLUMN_NAME FORMAT A20
COLUMN DATA_TYPE_INFO FORMAT A20
COLUMN NULLABLE FORMAT A8

SELECT 
    COLUMN_NAME,
    CASE 
        WHEN DATA_TYPE = 'NUMBER' AND DATA_PRECISION IS NOT NULL THEN 
            DATA_TYPE || '(' || DATA_PRECISION || ',' || NVL(DATA_SCALE, 0) || ')'
        WHEN DATA_TYPE IN ('VARCHAR2', 'CHAR') THEN 
            DATA_TYPE || '(' || DATA_LENGTH || ')'
        ELSE DATA_TYPE
    END AS DATA_TYPE_INFO,
    NULLABLE,
    COLUMN_ID
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
ORDER BY COLUMN_ID;

PROMPT
PROMPT === 3. 問題のあるカラムの詳細分析 ===
PROMPT *** マイグレーション対象カラムの現在の状態 ***

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    NULLABLE,
    CASE 
        WHEN NULLABLE = 'Y' THEN '✓ マイグレーション成功'
        ELSE '✗ マイグレーション未完了 - NOT NULL制約が残存'
    END AS MIGRATION_STATUS
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
AND COLUMN_NAME IN ('LINE_ID', 'MACHINE_ID', 'PART_ID', 'LINE', 'MACHINE', 'PART')
ORDER BY 
    CASE COLUMN_NAME
        WHEN 'LINE' THEN 1
        WHEN 'LINE_ID' THEN 2
        WHEN 'MACHINE' THEN 3
        WHEN 'MACHINE_ID' THEN 4
        WHEN 'PART' THEN 5
        WHEN 'PART_ID' THEN 6
    END;

PROMPT
PROMPT === 4. 制約の詳細確認 ===
SELECT 
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    CASE CONSTRAINT_TYPE
        WHEN 'P' THEN 'PRIMARY KEY'
        WHEN 'R' THEN 'FOREIGN KEY'
        WHEN 'C' THEN 'CHECK'
        WHEN 'U' THEN 'UNIQUE'
        ELSE CONSTRAINT_TYPE
    END AS CONSTRAINT_TYPE_DESC,
    STATUS
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
ORDER BY CONSTRAINT_TYPE;

PROMPT
PROMPT === 5. NOT NULL制約の具体的確認 ===
PROMPT *** システム生成のNOT NULL制約 ***
SELECT 
    CONSTRAINT_NAME,
    COLUMN_NAME,
    'NOT NULL制約' AS CONSTRAINT_DESC
FROM USER_CONS_COLUMNS UCC
JOIN USER_CONSTRAINTS UC ON UCC.CONSTRAINT_NAME = UC.CONSTRAINT_NAME
WHERE UC.TABLE_NAME = 'PRODUCTION_RESULT'
AND UC.CONSTRAINT_TYPE = 'C'
AND UCC.COLUMN_NAME IN ('LINE_ID', 'MACHINE_ID', 'PART_ID')
ORDER BY UCC.COLUMN_NAME;

PROMPT
PROMPT === 6. テーブル作成文の確認（メタデータから） ===
SELECT 
    'ALTER TABLE PRODUCTION_RESULT MODIFY (' || COLUMN_NAME || ' NULL);' AS SUGGESTED_FIX
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
AND COLUMN_NAME IN ('LINE_ID', 'MACHINE_ID', 'PART_ID')
AND NULLABLE = 'N';

PROMPT
PROMPT === 7. データ件数とサンプル確認 ===
SELECT COUNT(*) AS TOTAL_RECORDS FROM PRODUCTION_RESULT;

PROMPT
PROMPT === マイグレーション診断結果 ===
PROMPT
SELECT 
    '問題発見: ' || COUNT(*) || ' 個のカラムでNOT NULL制約が残存しています' AS DIAGNOSIS
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
AND COLUMN_NAME IN ('LINE_ID', 'MACHINE_ID', 'PART_ID')
AND NULLABLE = 'N';

PROMPT
PROMPT === 修正が必要なカラム ===
SELECT 
    COLUMN_NAME || ' -> NULL制約を削除する必要があります' AS REQUIRED_FIXES
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PRODUCTION_RESULT'
AND COLUMN_NAME IN ('LINE_ID', 'MACHINE_ID', 'PART_ID')
AND NULLABLE = 'N';

PROMPT
PROMPT ================================================================================
PROMPT 診断完了: マイグレーションは部分的にしか成功していません
PROMPT 文字列カラム(LINE, MACHINE, PART): 制約削除済み ✓
PROMPT 外部キーカラム(LINE_ID, MACHINE_ID, PART_ID): 制約が残存 ✗
PROMPT ================================================================================

EXIT;