# Generated by Django 4.2.7 on 2025-06-07 05:19

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('color', models.CharField(default='#007bff', help_text='HEX形式 (#RRGGBB)', max_length=7, verbose_name='色')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardCardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カード名')),
                ('is_visible', models.BooleanField(default=True, verbose_name='表示')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('alert_threshold_yellow', models.FloatField(default=80.0, verbose_name='黄色アラート閾値(%)')),
                ('alert_threshold_red', models.FloatField(default=80.0, verbose_name='赤色アラート閾値(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ダッシュボードカード設定',
                'verbose_name_plural': 'ダッシュボードカード設定',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ライン名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ライン',
                'verbose_name_plural': 'ライン',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='設備名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.line', verbose_name='ライン')),
            ],
            options={
                'verbose_name': '設備',
                'verbose_name_plural': '設備',
                'ordering': ['line', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='機種名')),
                ('part_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='品番')),
                ('target_pph', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='目標PPH')),
                ('cycle_time', models.FloatField(editable=False, verbose_name='サイクルタイム(秒)')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '機種',
                'verbose_name_plural': '機種',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('color', models.CharField(default='#6c757d', help_text='HEX形式 (#RRGGBB)', max_length=7, verbose_name='色')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('is_working', models.BooleanField(default=True, verbose_name='稼働日')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='祝日')),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='祝日名')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時間')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='休憩時間(分)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '稼働日',
                'verbose_name_plural': '稼働日',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(default=datetime.time(8, 30), verbose_name='稼働開始時間')),
                ('morning_meeting_duration', models.PositiveIntegerField(default=15, verbose_name='朝礼時間(分)')),
                ('break_times', models.JSONField(default=list, help_text='[{"start": "10:45", "end": "11:00"}, ...]', verbose_name='休憩時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.line', verbose_name='ライン')),
            ],
            options={
                'verbose_name': '稼働カレンダー',
                'verbose_name_plural': '稼働カレンダー',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'ライト'), ('dark', 'ダーク')], default='light', max_length=10, verbose_name='テーマ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_selected_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.line', verbose_name='最後に選択したライン')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー設定',
                'verbose_name_plural': 'ユーザー設定',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='タイムスタンプ')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='シリアル番号')),
                ('judgment', models.CharField(choices=[('OK', 'OK'), ('NG', 'NG')], max_length=2, verbose_name='判定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.line', verbose_name='ライン')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.machine', verbose_name='設備')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.part', verbose_name='機種')),
            ],
            options={
                'verbose_name': '実績',
                'verbose_name_plural': '実績',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='tags',
            field=models.ManyToManyField(blank=True, to='production.tag', verbose_name='タグ'),
        ),
        migrations.CreateModel(
            name='UserLineAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.line', verbose_name='ライン')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザーラインアクセス',
                'verbose_name_plural': 'ユーザーラインアクセス',
                'unique_together': {('user', 'line')},
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(default=datetime.time(8, 0), verbose_name='開始時間')),
                ('end_time', models.TimeField(default=datetime.time(17, 0), verbose_name='終了時間')),
                ('planned_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='計画数量')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='順番')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.line', verbose_name='ライン')),
                ('machine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.machine', verbose_name='機械')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.part', verbose_name='機種')),
            ],
            options={
                'verbose_name': '生産計画',
                'verbose_name_plural': '生産計画',
                'ordering': ['date', 'line', 'start_time'],
                'unique_together': {('date', 'line', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='PartChangeDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='ダウンタイム(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('from_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_from', to='production.part', verbose_name='切替前機種')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.line', verbose_name='ライン')),
                ('to_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_to', to='production.part', verbose_name='切替後機種')),
            ],
            options={
                'verbose_name': '機種切替ダウンタイム',
                'verbose_name_plural': '機種切替ダウンタイム',
                'unique_together': {('line', 'from_part', 'to_part')},
            },
        ),
    ]
