# Generated by Django 4.2.7 on 2025-06-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_add_planned_hourly_production'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plannedhourlyproduction',
            unique_together={('date', 'line', 'part', 'hour')},
        ),
        migrations.RemoveField(
            model_name='plannedhourlyproduction',
            name='machine',
        ),
    ]
