# Generated by Django 4.2.7 on 2025-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_plannedhourlyproduction_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_production_active',
            field=models.BooleanField(default=False, help_text='この設備が現在生産稼働中かを示すフラグ', verbose_name='生産稼働中'),
        ),
        migrations.AlterField(
            model_name='result',
            name='serial_number',
            field=models.CharField(max_length=100, verbose_name='シリアル番号'),
        ),
    ]
