# Generated by Django 4.2.7 on 2025-06-11 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0005_add_machine_production_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardcardsetting',
            options={'ordering': ['sequence'], 'verbose_name': 'ダッシュボードカード設定', 'verbose_name_plural': 'ダッシュボードカード設定'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['category', 'name'], 'verbose_name': '機種', 'verbose_name_plural': '機種'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-date', 'sequence'], 'verbose_name': '生産計画', 'verbose_name_plural': '生産計画'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-timestamp'], 'verbose_name': '生産実績', 'verbose_name_plural': '生産実績'},
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dashboardcardsetting',
            name='alert_threshold_red',
        ),
        migrations.RemoveField(
            model_name='dashboardcardsetting',
            name='alert_threshold_yellow',
        ),
        migrations.RemoveField(
            model_name='dashboardcardsetting',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='dashboardcardsetting',
            name='order',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='is_production_active',
        ),
        migrations.RemoveField(
            model_name='part',
            name='cycle_time',
        ),
        migrations.RemoveField(
            model_name='part',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='part',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='part',
            name='target_pph',
        ),
        migrations.RemoveField(
            model_name='result',
            name='line',
        ),
        migrations.RemoveField(
            model_name='result',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='result',
            name='part',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_active',
        ),
        migrations.AddField(
            model_name='dashboardcardsetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AddField(
            model_name='dashboardcardsetting',
            name='sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順序'),
        ),
        migrations.AddField(
            model_name='dashboardcardsetting',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='タイトル'),
        ),
        migrations.AddField(
            model_name='part',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='機種コード'),
        ),
        migrations.AddField(
            model_name='plan',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='計画数量'),
        ),
        migrations.AddField(
            model_name='result',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='dashboardcardsetting',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=100, verbose_name='機種名'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.part', verbose_name='機種'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sequence',
            field=models.PositiveIntegerField(verbose_name='順序'),
        ),
        migrations.AlterField(
            model_name='result',
            name='judgment',
            field=models.CharField(choices=[('OK', '良品'), ('NG', '不良品')], max_length=2, verbose_name='判定'),
        ),
        migrations.AlterField(
            model_name='result',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.plan', verbose_name='計画'),
        ),
        migrations.AlterField(
            model_name='result',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='result',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='シリアル番号'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='タグ名'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('line', 'date', 'sequence')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_no1', models.CharField(blank=True, max_length=10, null=True, verbose_name='拠点コード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
        migrations.RemoveField(
            model_name='plan',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='planned_quantity',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start_time',
        ),
    ]
