# Generated by Django 4.2.7 on 2025-06-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_dashboardcardsetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='sta_no1',
            field=models.CharField(default='DEFAULT', max_length=50, verbose_name='拠点コード'),
        ),
        migrations.AddField(
            model_name='line',
            name='sta_no2',
            field=models.CharField(default='DEFAULT', max_length=50, verbose_name='ステーション番号'),
        ),
    ]
