# Generated by Django 4.2.7 on 2025-07-03 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0008_alter_dashboardcardsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('status', models.CharField(choices=[('new', '新規'), ('in_progress', '対応中'), ('completed', '完了'), ('rejected', '却下')], default='new', max_length=20, verbose_name='状態')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'フィードバック',
                'verbose_name_plural': 'フィードバック一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
