# Generated by Django 4.2.7 on 2025-07-03 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0009_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'フィードバック', 'verbose_name_plural': 'フィードバック'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='content',
        ),
        migrations.AddField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/', verbose_name='添付ファイル'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('feature', '機能改善'), ('bug', 'バグ報告'), ('ui_ux', 'UI/UX改善'), ('other', 'その他')], default='other', max_length=10, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.TextField(default='', verbose_name='詳細内容'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='page_url',
            field=models.URLField(blank=True, verbose_name='送信時のURL'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='優先度'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', '新規'), ('in_review', '確認中'), ('in_progress', '対応中'), ('completed', '完了'), ('rejected', '却下')], default='new', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='送信者'),
        ),
    ]
