# Generated by Django 4.2.7 on 2025-07-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_feedback_options_remove_feedback_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
    ]
