# Generated by Django 4.2.7 on 2025-07-16 02:55

from django.db import migrations


def migrate_result_plan_data(apps, schema_editor):
    """plan列のデータをline, machine, partフィールドに移行"""
    # この処理はスキップして後で手動で実行
    pass


def reverse_migrate_result_plan_data(apps, schema_editor):
    """逆マイグレーション（rollback時）- plan列にデータを戻す"""
    # 逆マイグレーションは複雑なため、何もしない
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_remove_feedback_title'),
    ]

    operations = [
        migrations.RunPython(
            migrate_result_plan_data,
            reverse_migrate_result_plan_data
        ),
    ]
