# Generated by Django 4.2.7 on 2025-08-04 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_optimized_result_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='対象日付')),
                ('forecast_completion_time', models.TimeField(blank=True, null=True, verbose_name='予測完了時刻')),
                ('calculation_timestamp', models.DateTimeField(verbose_name='計算実行時刻')),
                ('current_production_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='現在の生産速度')),
                ('total_planned_quantity', models.PositiveIntegerField(default=0, verbose_name='計画総数量')),
                ('total_actual_quantity', models.PositiveIntegerField(default=0, verbose_name='実績総数量')),
                ('is_delayed', models.BooleanField(default=False, verbose_name='遅延予測')),
                ('confidence_level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='信頼度')),
                ('is_next_day', models.BooleanField(default=False, verbose_name='翌日')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '生産終了予測',
                'verbose_name_plural': '生産終了予測',
                'ordering': ['-target_date', 'line'],
            },
        ),
        migrations.CreateModel(
            name='ProductionForecastSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_interval_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='計算間隔(分)')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '終了予測設定',
                'verbose_name_plural': '終了予測設定',
            },
        ),
        migrations.RenameIndex(
            model_name='weeklyresultaggregation',
            new_name='production__date_f0ecff_idx',
            old_name='production_w_date_li_b8e8a5_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyresultaggregation',
            new_name='production__date_2a3d92_idx',
            old_name='production_w_date_li_8c4b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyresultaggregation',
            new_name='production__date_406af8_idx',
            old_name='production_w_date_li_f9c3d1_idx',
        ),
        migrations.AddField(
            model_name='productionforecastsettings',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.line', verbose_name='ライン'),
        ),
        migrations.AddField(
            model_name='productionforecast',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.line', verbose_name='ライン'),
        ),
        migrations.AlterUniqueTogether(
            name='productionforecast',
            unique_together={('line', 'target_date')},
        ),
    ]
