# Generated by Django 4.2.7 on 2025-08-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_machine_is_count_target_alter_result_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcardsetting',
            name='card_type',
            field=models.CharField(default='unknown', help_text='カードの識別子（例: total_planned, total_actual）', max_length=50, verbose_name='カードタイプ'),
        ),
        migrations.AddField(
            model_name='dashboardcardsetting',
            name='description',
            field=models.TextField(blank=True, help_text='このカードの説明や用途', verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='dashboardcardsetting',
            name='is_system_card',
            field=models.BooleanField(default=False, help_text='システム標準のカード（削除不可）', verbose_name='システムカード'),
        ),
        migrations.AddIndex(
            model_name='dashboardcardsetting',
            index=models.Index(fields=['is_visible', 'order'], name='production__is_visi_e4f83c_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardcardsetting',
            index=models.Index(fields=['card_type'], name='production__card_ty_c43386_idx'),
        ),
    ]
