# Generated by Django 4.2.7 on 2025-08-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_optimize_dashboard_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcardsetting',
            name='alert_threshold_red',
            field=models.FloatField(default=80.0, help_text='達成率がこの値を下回ると赤色のアラートが表示されます。通常は黄色閾値より低い値を設定します。', verbose_name='赤色アラート閾値(%)'),
        ),
        migrations.AlterField(
            model_name='dashboardcardsetting',
            name='alert_threshold_yellow',
            field=models.FloatField(default=80.0, help_text='達成率がこの値を下回ると黄色のアラートが表示されます。0-100の範囲で設定してください。', verbose_name='黄色アラート閾値(%)'),
        ),
        migrations.AlterField(
            model_name='dashboardcardsetting',
            name='card_type',
            field=models.CharField(default='unknown', help_text='カードの識別子です（例: total_planned, total_actual, achievement_rate）。システムが内部的に使用します。', max_length=50, unique=True, verbose_name='カードタイプ'),
        ),
        migrations.AlterField(
            model_name='dashboardcardsetting',
            name='description',
            field=models.TextField(blank=True, help_text='このカードの詳細説明や用途を記載してください。管理画面でのメモとして使用されます。', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='dashboardcardsetting',
            name='is_system_card',
            field=models.BooleanField(default=False, help_text='システム標準のカードです。チェックされたカードは削除することができません。', verbose_name='システムカード'),
        ),
        migrations.AlterField(
            model_name='dashboardcardsetting',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='チェックするとダッシュボードにこのカードが表示されます。チェックを外すとカードは非表示になります。', verbose_name='表示'),
        ),
        migrations.AlterField(
            model_name='dashboardcardsetting',
            name='name',
            field=models.CharField(help_text='ダッシュボードに表示されるカードの名前です。他のカードと重複しない一意の名前を設定してください。', max_length=100, unique=True, verbose_name='カード名'),
        ),
        migrations.AlterField(
            model_name='dashboardcardsetting',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ダッシュボードでのカードの表示順序です。小さい数値ほど上に表示されます。同じ順序の場合はカード名順に並びます。', verbose_name='表示順'),
        ),
    ]
