# Generated by Django 4.2.7 on 2025-08-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_alter_dashboardcardsetting_alert_threshold_red_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name'], 'verbose_name': '機種', 'verbose_name_plural': '機種'},
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='機種名'),
        ),
        migrations.RemoveField(
            model_name='part',
            name='line',
        ),
    ]
